# Generated by Django 4.0.3 on 2022-07-06 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_school_delete_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='content',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='content',
        ),
        migrations.RemoveField(
            model_name='school',
            name='content',
        ),
    ]
