# Generated by Django 4.0.3 on 2022-07-06 14:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_interest_content_remove_requirement_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='c_school',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='core.school'),
            preserve_default=False,
        ),
    ]
