# Generated by Django 4.0.3 on 2022-07-06 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_course_funding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funfact',
            name='content',
        ),
    ]
