# Generated by Django 4.0.3 on 2022-07-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_funfact_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='s_requirement',
            field=models.ManyToManyField(null=True, to='core.requirement'),
        ),
    ]
