# Generated by Django 4.0.3 on 2022-07-06 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_scholarship_s_requirement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='content',
        ),
    ]
