# Generated by Django 4.0.3 on 2022-07-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_course_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.AlterField(
            model_name='about',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='summary',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='summary',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='summary',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='notice',
            name='summary',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='research',
            name='summary',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='summary',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='summary',
            field=models.TextField(default=''),
        ),
    ]
