# Generated by Django 4.0.3 on 2022-07-08 15:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_course_image_alter_about_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/courses'),
            preserve_default=False,
        ),
    ]
