# Generated by Django 4.0.3 on 2022-07-08 16:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/teachers'),
            preserve_default=False,
        ),
    ]
