# Generated by Django 4.0.3 on 2022-07-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_teacher_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='address',
            field=models.CharField(default='Default, Setting', max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(default='default@ex.co.ke', max_length=254),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(default='+254 700 000 000', max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='social_media',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
