# Generated by Django 4.0.3 on 2022-07-08 20:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_teacher_address_alter_teacher_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/blog'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/events'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='research',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/research'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scholarship',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/scholarship'),
            preserve_default=False,
        ),
    ]
