# Generated by Django 4.0.3 on 2022-07-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_blog_image_event_image_research_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='s_requirement',
            field=models.ManyToManyField(to='core.requirement'),
        ),
    ]
