# Generated by Django 4.0.3 on 2022-07-10 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_scholarship_s_requirement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.RemoveField(
            model_name='research',
            name='image',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='image',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='image',
        ),
    ]
