# Generated by Django 4.0.3 on 2022-07-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_blog_image_course_image_event_image_research_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.RemoveField(
            model_name='research',
            name='image',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='image',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='image',
        ),
        migrations.AddField(
            model_name='blog',
            name='image_url',
            field=models.ImageField(null=True, upload_to='images/blog/'),
        ),
        migrations.AddField(
            model_name='course',
            name='image_url',
            field=models.ImageField(null=True, upload_to='images/courses/'),
        ),
        migrations.AddField(
            model_name='event',
            name='image_url',
            field=models.ImageField(null=True, upload_to='images/events/'),
        ),
        migrations.AddField(
            model_name='research',
            name='image_url',
            field=models.ImageField(null=True, upload_to='images/research/'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='image_url',
            field=models.ImageField(null=True, upload_to='images/scholarship/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='image_url',
            field=models.ImageField(null=True, upload_to='images/teachers/'),
        ),
    ]
