# Generated by Django 4.0.3 on 2022-07-15 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_blog_image_remove_course_image_and_more'),
    ]

    operations = [
       
    ]
