# Generated by Django 4.0.3 on 2022-07-15 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_blog_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['heading']},
        ),
    ]
