# Generated by Django 4.0.3 on 2022-07-15 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_blog_author_alter_blog_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='name',
        ),
    ]
