# Generated by Django 4.0.3 on 2022-07-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_blog_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='fees',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='funding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
