# Generated by Django 4.0.3 on 2022-07-18 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_course_fees_alter_course_funding'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='header_about',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.about'),
        ),
        migrations.AddField(
            model_name='course',
            name='header_about',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.about'),
        ),
        migrations.AddField(
            model_name='event',
            name='header_about',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.about'),
        ),
        migrations.AddField(
            model_name='funfact',
            name='header_about',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.about'),
        ),
        migrations.AddField(
            model_name='interest',
            name='header_about',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.about'),
        ),
        migrations.AddField(
            model_name='notice',
            name='header_about',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.about'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='header_about',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.about'),
        ),
        migrations.AddField(
            model_name='research',
            name='header_about',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.about'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='header_about',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.about'),
        ),
        migrations.AddField(
            model_name='school',
            name='header_about',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.about'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='header_about',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.about'),
        ),
    ]
