# Generated by Django 4.0.3 on 2022-07-18 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_blog_header_about_course_header_about_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='summary',
        ),
    ]
