# Generated by Django 4.0.3 on 2022-07-18 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_blog_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='event',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='research',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='summary',
        ),
    ]
