# Generated by Django 4.0.3 on 2022-07-18 17:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_course_summary_remove_event_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='teacher',
            name='summary',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
