# Generated by Django 4.0.3 on 2022-07-18 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_research_content_teacher_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='content',
        ),
    ]
