# Generated by Django 4.0.3 on 2022-07-18 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_scholarship_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='s_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school'),
        ),
    ]
