# Generated by Django 4.0.3 on 2022-07-18 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_scholarship_s_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='s_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.school'),
        ),
    ]
