# Generated by Django 4.0.3 on 2022-07-18 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_scholarship_s_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='header_about',
        ),
    ]
