# Generated by Django 4.0.3 on 2022-07-06 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.RemoveField(
            model_name='course',
            name='c_requirement',
        ),
        migrations.RemoveField(
            model_name='course',
            name='c_teacher',
        ),
        migrations.RemoveField(
            model_name='event',
            name='e_speaker',
        ),
        migrations.DeleteModel(
            name='FunFact',
        ),
        migrations.DeleteModel(
            name='Notice',
        ),
        migrations.DeleteModel(
            name='Research',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='s_course',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='t_courses',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='t_interest',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
        migrations.DeleteModel(
            name='Requirement',
        ),
        migrations.DeleteModel(
            name='Scholarship',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
